Improve generate-certs-and-keystore script and update readme.

diff --git a/bin/generate-certs-and-keystore b/bin/generate-certs-and-keystore
--- a/bin/generate-certs-and-keystore
+++ b/bin/generate-certs-and-keystore
@@ -1,7 +1,14 @@
 #!/usr/bin/env bash
 project_home="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 
-flow_collector_host=10.0.37.14
+if [ $# -eq 0 ]; then
+  echo "Missing flow collector hostname or IP address"
+  echo ""
+  echo "usage: generate-certs-and-keystore flow-collector-ip-or-hostname"
+  exit 1
+fi
+
+flow_collector_host=$1
 flow_collector_certificate_alias=${flow_collector_host}
 
 data_exporter_certificate_authority_name=data-exporter-certificate-authority
